# =============================================================================
# GENERATED BY NEXUS IDP SCAFFOLDER — DO NOT EDIT MANUALLY
# =============================================================================

# -----------------------------------------------------------------------------
# OBLIGATOIRE — Identité de la souscription
# -----------------------------------------------------------------------------
subscription_alias_name: "{{ values.subscriptionName }}-{{ values.environment }}"
subscription_display_name: "{{ values.subscriptionName | capitalize }} - {{ values.environment | upper }}"

subscription_workload: "{{ values.workload }}"

# -----------------------------------------------------------------------------
# OBLIGATOIRE — Management Group
# -----------------------------------------------------------------------------
subscription_management_group_id: "{{ values.managementGroupId }}"

# -----------------------------------------------------------------------------
# Tags
# -----------------------------------------------------------------------------
subscription_tags:
  environment:  "{{ values.environment }}"
  cost_center:  "{{ values.costCenter }}"
  owner:        "{{ values.owner }}"
  managed_by:   "terraform"
  application:  "{{ values.subscriptionName }}"
  region:       "{{ values.region }}"

# -----------------------------------------------------------------------------
# Resource Groups
# -----------------------------------------------------------------------------
resource_group_creation_enabled: {{ values.resourceGroupCreationEnabled | lower }}


# -----------------------------------------------------------------------------
# Role Assignments
# -----------------------------------------------------------------------------
role_assignment_enabled: {{ values.roleAssignmentEnabled | lower }}


# -----------------------------------------------------------------------------
# Budgets
# -----------------------------------------------------------------------------
budget_enabled: {{ values.budgetEnabled | lower }}


# -----------------------------------------------------------------------------
# Resource Providers
# -----------------------------------------------------------------------------
subscription_register_resource_providers_enabled: {{ values.registerProvidersEnabled | lower }}


# -----------------------------------------------------------------------------
# Managed Identities
# -----------------------------------------------------------------------------


# -----------------------------------------------------------------------------
# Localisation
# -----------------------------------------------------------------------------
location: "{{ values.region }}"

# -----------------------------------------------------------------------------
# Souscription existante
# -----------------------------------------------------------------------------
subscription_alias_enabled: {{ values.subscriptionAliasEnabled | lower }}