---
name: gitleaks

on:
    pull_request:
    push:
        branches: [main]

permissions:
    contents: read

jobs:
    scan:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
              with:
                  fetch-depth: 0 # nécessaire pour scanner tout l'historique du diff

            - name: Run gitleaks
              run: |
                  docker run --rm -v "$(pwd):/repo" zricethezav/gitleaks:latest \
                    detect --source /repo -v --exit-code 1
